"""Product-facing safety and audit contracts around frozen CoachIQ research."""

from coachiq.product.audit import (
    AuditMode,
    CandidateEvaluation,
    DecisionPublicationRecord,
    FrozenModels,
    GameAudit,
    SourceMetadata,
    WeeklyAudit,
    aggregate_week_audits,
    assemble_game_audit,
    audit_game,
    audit_week,
    evaluate_candidate,
    fingerprint_frame,
    fit_chronological_models,
    fit_frozen_models,
    publication_record_from_evaluation,
    publication_safe_language,
    stable_json_dumps,
    validate_audit_boundary,
    validate_policy_development_boundary,
)
from coachiq.product.publication import (
    PUBLICATION_POLICY_V1,
    PUBLICATION_POLICY_VERSION,
    PublicationDecision,
    PublicationPolicy,
    SafetyDiagnostics,
    apply_publication_policy,
    transition_clipping_diagnostics,
)

__all__ = [
    "AuditMode",
    "CandidateEvaluation",
    "DecisionPublicationRecord",
    "FrozenModels",
    "GameAudit",
    "PUBLICATION_POLICY_V1",
    "PUBLICATION_POLICY_VERSION",
    "PublicationDecision",
    "PublicationPolicy",
    "SafetyDiagnostics",
    "SourceMetadata",
    "WeeklyAudit",
    "aggregate_week_audits",
    "apply_publication_policy",
    "assemble_game_audit",
    "audit_game",
    "audit_week",
    "evaluate_candidate",
    "fingerprint_frame",
    "fit_chronological_models",
    "fit_frozen_models",
    "publication_safe_language",
    "publication_record_from_evaluation",
    "stable_json_dumps",
    "transition_clipping_diagnostics",
    "validate_audit_boundary",
    "validate_policy_development_boundary",
]
